package com.nirocca.ornithoalert.util;

import java.io.File;
import java.io.IOException;
import java.nio.charset.Charset;

import org.apache.commons.io.FileUtils;
import org.apache.commons.io.IOUtils;

public class BirdingtoursNaturguckerScriptCreator {
  private static final String MAIN_FILE = "naturgucker_main.js";
  private static final String FRAGMENT_FILE = "naturgucker_fragment.js";
  private static final String[] SPECIES = { // generated by BirdingtoursSpeciesListAnalyzer for a specific day
      "Höckerschwan",
      "Graugans",
      "Stockente",
      "Haubentaucher",
      "Kormoran",
      "Silberreiher",
      "Graureiher",
      "Seeadler",
      "Rotmilan",
      "Mäusebussard",
      "Blässhuhn",
      "Kranich",
      "Lachmöwe",
      "Ringeltaube",
      "Grünspecht",
      "Buntspecht",
      "Rauchschwalbe",
      "Rotkehlchen",
      "Hausrotschwanz",
      "Singdrossel",
      "Amsel",
      "Kohlmeise",
      "Blaumeise",
      "Bartmeise",
      "Kleiber",
      "Gartenbaumläufer",
      "Eichelhäher",
      "Nebelkrähe",
      "Kolkrabe",
      "Star",
      "Haussperling",
      "Buchfink",
      "Waldbaumläufer",
  };

  public static void main(String[] args) throws IOException {
    String main = IOUtils.toString(BirdingtoursNaturguckerScriptCreator.class.getResourceAsStream("/" + MAIN_FILE), Charset.defaultCharset());
    String fragment = IOUtils.toString(BirdingtoursNaturguckerScriptCreator.class.getResourceAsStream("/" + FRAGMENT_FILE), Charset.defaultCharset());
    String fragments = createFragments(fragment);
    File outFile = new File("target/naturgucker.js");
    FileUtils.write(outFile, main.replace("FRAGMENTS", fragments), Charset.defaultCharset());
    System.out.println("Written to " + outFile.getAbsolutePath());
  }

  private static String createFragments(String fragment) {
    StringBuilder builder = new StringBuilder();
    for (String species : SPECIES) {
      builder.append(fragment.replace("BIRD_NAME", species));
    }
    return builder.deleteCharAt(builder.length() - 1).toString();
  }
}
