package com.nirocca.ornithoalert.util;

import java.io.IOException;
import java.nio.charset.Charset;

import org.apache.commons.io.IOUtils;
// NOT REALLY WORKING
public class BirdingtoursNaturguckerScriptCreator {
  private static final String FRAGMENT_FILE = "naturgucker_fragment.js";
  private static final String[] SPECIES = { // generated by BirdingtoursSpeciesListAnalyzer for a specific day
      "Turmfalke",
      "Kranich",
      "Ringeltaube",
      "Wiesenpieper",
      "Singdrossel",
      "Wintergoldhähnchen",
      "Kohlmeise",
      "Blaumeise",
      "Eichelhäher",
      "Dohle",
      "Nebelkrähe",
      "Kolkrabe",
      "Star",
      "Haussperling",
      "Buchfink",
  };

  public static void main(String[] args) throws IOException {
    String fragment = IOUtils.toString(BirdingtoursNaturguckerScriptCreator.class.getResourceAsStream("/" + FRAGMENT_FILE), Charset.defaultCharset());
    for (String species : SPECIES) {
      System.out.println(fragment.replace("BIRD_NAME", species));
    }
  }
}
